apiVersion: batch/v1
kind: Job
metadata:
  name: demo-sklearn-k8s
spec:
  template:
    spec:
      containers:
      - name: tdemo-sklearn-k8s
        imagePullPolicy: Always
        image: ghcr.io/qige96/k8s-docker-ml-test1:demo-sklearn
        command: ["python3",  "sklearn_job.py"]
      restartPolicy: Never
  backoffLimit: 0